# Release script: build + push both :vX.Y.Z and :stable
# Usage:
#   .\RELEASE.ps1 -Username yourDockerHubUser -Version 0.1.1
#   .\RELEASE.ps1   (interactive)
#
# Result:
# - Builds YOURUSER/checkers-ai:vX.Y.Z
# - Tags YOURUSER/checkers-ai:stable
# - Pushes BOTH
# - Writes .env with CHECKERS_AI_IMAGE=...:stable

param(
    [string]$Username,
    [string]$Version,
    [string]$RepoName = "checkers-ai"
)

$ErrorActionPreference = "Stop"

function Fail([string]$Message) {
    Write-Host "[ERROR] $Message" -ForegroundColor Red
    exit 1
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Release to Docker Hub (v + stable)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# 1. Check for Docker
try {
    $dockerVer = docker --version
    Write-Host "[OK] Docker found: $dockerVer" -ForegroundColor Green
} catch {
    Fail "Docker not found. Install Docker Desktop and restart your terminal."
}

# 2. Collect inputs
if (-not $Username) {
    $Username = Read-Host "Enter your Docker Hub username"
}
if (-not $Username) {
    Fail "Username is required."
}

if (-not $Version) {
    $Version = Read-Host "Enter version (example: 0.1.1)"
}
if (-not $Version) {
    Fail "Version is required."
}

# Normalize version/tag
$normalized = $Version.Trim()
if ($normalized.StartsWith("v")) {
    $normalized = $normalized.Substring(1)
}

if ($normalized -notmatch '^\d+\.\d+\.\d+$') {
    Fail "Version must look like 0.1.1 (semver: major.minor.patch)."
}

$tagVersion = "v$normalized"

$ImageName = "$Username/$RepoName"
$colon = [char]58
$ImageVersion = $ImageName + $colon + $tagVersion
$ImageStable = $ImageName + $colon + 'stable'

Write-Host "Target images:" -ForegroundColor Yellow
Write-Host "  - $ImageVersion" -ForegroundColor Yellow
Write-Host "  - $ImageStable" -ForegroundColor Yellow
Write-Host ""

# 3. Login
Write-Host "[1/4] Docker login..." -ForegroundColor Cyan
Write-Host "You may be prompted to authenticate." -ForegroundColor Gray
docker login
if ($LASTEXITCODE -ne 0) {
    Fail "Docker login failed."
}

# 4. Build versioned image
Write-Host "[2/4] Building backend image ($ImageVersion)..." -ForegroundColor Cyan
docker build -t $ImageVersion .
if ($LASTEXITCODE -ne 0) {
    Fail "Docker build failed."
}

# 5. Tag stable
Write-Host "[3/4] Tagging stable ($ImageStable)..." -ForegroundColor Cyan
docker tag $ImageVersion $ImageStable
if ($LASTEXITCODE -ne 0) {
    Fail "Docker tag failed."
}

# 6. Push both
Write-Host "[4/4] Pushing tags..." -ForegroundColor Cyan
docker push $ImageVersion
if ($LASTEXITCODE -ne 0) {
    Fail "Push failed for $ImageVersion"
}

docker push $ImageStable
if ($LASTEXITCODE -ne 0) {
    Fail "Push failed for $ImageStable"
}

# 7. Write .env for local / distribution
$EnvFile = ".env"
$EnvContent = @(
    "# Auto-generated by RELEASE.ps1",
    "CHECKERS_AI_IMAGE=$ImageStable",
    "CHECKERS_AI_CHECKPOINT_RELOAD_INTERVAL_SEC=2.0"
) -join "`n"

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-Host "" 
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  SUCCESS" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Pushed:" -ForegroundColor Green
Write-Host "  - $ImageVersion" -ForegroundColor Green
Write-Host "  - $ImageStable" -ForegroundColor Green
Write-Host "" 
Write-Host "Updated .env:" -ForegroundColor Green
Write-Host "  CHECKERS_AI_IMAGE=$ImageStable" -ForegroundColor Green
Write-Host "" 
Write-Host "Next: run one of these:" -ForegroundColor Cyan
Write-Host "  docker compose -f docker-compose.web.yml up -d" -ForegroundColor Gray
Write-Host "  docker compose -f docker-compose.image.yml up -d" -ForegroundColor Gray
